### ISSUE TITLE
Lists not showing markers in Markdown component

### ISSUE THREAD

**Issue by HaveF** [rclement/datasette-dashboards#139]
Hi, 😄 

I found that markdown didn't show quite consistently.

```sql
select '# Analysis details

We wanted to analyze data from job offers, using the **`python` search keyword**
from three sources of job-boards:
[APEC](https://www.apec.fr),
[Indeed](https://fr.indeed.com/) and
[RegionsJob](https://regionsjob.com).

## Process

The process was in 3 steps:

* Extraction
* Transformation
* Loading

After the ETL process, an extra data enrichment step was developed to provide
location geocoding, based on place names.

## SQL query

```sql
SELECT
  date(date) as day,
  count(*) as count
FROM offers_view
GROUP BY day
ORDER BY day
```'
as demo_markdown
```

![image](https://github.com/rclement/datasette-dashboards/assets/54462/57ddcbd6-f143-4d17-aa37-f5da606665be)

But when display in [dashboars](https://datasette-dashboards-demo.vercel.app/-/dashboards/job-offers-stats?date_start=2021-01-01), there is no `*` before list items

![image](https://github.com/rclement/datasette-dashboards/assets/54462/32257739-169d-4e20-b235-e3dc0c009b37)

**Comment by HaveF** [comment]
Oh, the sql part is also not right... there should no `sql` before `SELECT`
```sql
SELECT
  date(date) as day,
  count(*) as count
FROM offers_view
GROUP BY day
ORDER BY day
```

**Comment by rclement** [comment]
Thanks @HaveF for catching and reporting this issue!

> But when display in [dashboars](https://datasette-dashboards-demo.vercel.app/-/dashboards/job-offers-stats?date_start=2021-01-01), there is no * before list items

Indeed, there seem to be an issue with the Markdown rendering. I'll look for the culprit and see if I can fix it.

> Oh, the sql part is also not right... there should no sql before SELECT

Mmmh interesting, this means the Markdown rendering does not support properly code blocks with language syntax highlighting (it could be rendered all monospace black but still skip the language information)

**Comment by rclement** [comment]
Ok here is the default style concerning ordered and unordered list in Datasette:

```css
ol, ul {
  list-style: none;
}
```

We might have to override this style using the Datasette Dashboard stylesheet to restore bullet and numbered list only for the Markdown chart component.

**Comment by HaveF** [comment]
Could it possible add class `col-demo_markdown`? This will ensure consistency with datasettle, as we don't know if there are any other inconsistencies besides the `list-style`.

Here is [ref](https://datasette-dashboards-demo.vercel.app/jobs?sql=select+%27%23+Analysis+details%0D%0A%0D%0AWe+wanted+to+analyze+data+from+job+offers%2C+using+the+**%60python%60+search+keyword**%0D%0Afrom+three+sources+of+job-boards%3A%0D%0A%5BAPEC%5D%28https%3A%2F%2Fwww.apec.fr%29%2C%0D%0A%5BIndeed%5D%28https%3A%2F%2Ffr.indeed.com%2F%29+and%0D%0A%5BRegionsJob%5D%28https%3A%2F%2Fregionsjob.com%29.%0D%0A%0D%0A%23%23+Process%0D%0A%0D%0AThe+process+was+in+3+steps%3A%0D%0A%0D%0A*+Extraction%0D%0A*+Transformation%0D%0A*+Loading%0D%0A%0D%0AAfter+the+ETL+process%2C+an+extra+data+enrichment+step+was+developed+to+provide%0D%0Alocation+geocoding%2C+based+on+place+names.%0D%0A%0D%0A%23%23+SQL+query%0D%0A%0D%0A%60%60%60sql%0D%0ASELECT%0D%0A++date%28date%29+as+day%2C%0D%0A++count%28*%29+as+count%0D%0AFROM+offers_view%0D%0AGROUP+BY+day%0D%0AORDER+BY+day%0D%0A%60%60%60%27%0D%0Aas+demo_markdown).

![image](https://github.com/rclement/datasette-dashboards/assets/54462/b68b43b8-d26f-4f1e-9d5f-609253e5a24c)
