### ISSUE TITLE
Add support for Vega charts

### ISSUE THREAD

**Issue by rclement** [rclement/datasette-dashboards#63]
Only Vega-Lite charts are currently supported using the `vega` library. It would be useful to support both specifications.

**Comment by rclement** [comment]
Here are some examples of Vega charts: https://vega.github.io/vega/examples/
Here are some examples of Vega-Lite charts: https://vega.github.io/vega-lite/examples/

**Comment by lukasdei** [comment]
Hey. Sorry for the slow reply. That looks super cool! I did find a bug tho. I tried it in both Firefox 110.0.1 and Chrome 110.0.5481.177. In both browsers, the word cloud chart rendered, but when the window resizes, the chart container just grows continuously. 

https://user-images.githubusercontent.com/42354339/224522305-1d13dfab-7043-4ef1-addf-d01b3e8cc0ad.mov

However, if just the word cloud is being displayed, the chart resizes without issue. 

https://user-images.githubusercontent.com/42354339/224522321-62566470-6c8a-4689-838d-e4f9af38ce76.mov

Thoughts?

**Comment by rclement** [comment]
Thank you @lukasdei for the feedback!

I also got the "height resizing" bug on my side, no idea of the root cause for the moment

**Comment by rclement** [comment]
@lukasdei I managed to find a workaround in 8ce9bc0:
- In dashboard view: responsive width only (the height need to be set either manually or by the chart itself)
- In chart view: responsive width and height

This is aligned with the current responsive implementation for Vega-Lite charts

**Comment by rclement** [comment]
I am pretty happy with the current implementation so I will merge the PR #64. Further enhancements will be performed down the line when needs arrive

**Comment by lukasdei** [comment]
Works great on my end. Thanks so much for working on this! 😁😁
